version: '3'

services:
  mySQL:
    image: mysql:8.0.33
    restart: always
    container_name: mySQLdb
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql